---
name: File-Lockfile
version: v1.0.3
author:
  - 'Sergey Sinkovskiy <glorybox@cpan.org>'
abstract: create lockfile to prevent process simultaneous run
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Data::Inheritable: 0.06
  File::Temp: 0.21
  perl: v5.6.1
configure_requires:
  Module::Build: 0.35
provides:
  File::Lockfile:
    file: lib/File/Lockfile.pm
    version: v1.0.3
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
